GET http://localhost:3000

###

GET http://localhost:3000/personnages

###

GET http://localhost:3000/error



###

GET http://localhost:3000/personnages/66150db3805e22e53f4ebc12

### 

POST http://localhost:3000/personnages
Content-Type: application/json

{
  "name": "Vegeta",
  "race": "Saiyan",
  "powerLevel": 9000,
  "transformations": ["Super Saiyan", "Super Saiyan 2", "Super Saiyan 3", "Super Saiyan God", "Ultra Instinct"],
  "friends": ["Krillin", "Piccolo", "Gohan", "Tien", "Yamcha", "Chiaotzu", "Bulma"],
  "enemies": ["Frieza", "Cell", "Majin Buu"]
}

### 

PUT http://localhost:3000/personnages/1
Content-Type: application/json

{
  "name": "test",
  "race": "test",
  "powerLevel": 500,
  "transformations": ["Super Saiyan", "Super Saiyan 2", "Super Saiyan 3", "Super Saiyan God", "Ultra Instinct"],
  "friends": ["Krillin", "Piccolo", "Gohan", "Tien", "Yamcha", "Chiaotzu", "Bulma"],
  "enemies": ["Frieza", "Cell", "Majin Buu"]
}

###

DELETE http://localhost:3000/personnages/66150db3805e22e53f4ebc12


### 

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "admin",
    "password": "admin"
} 

###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "admin",
    "password": "admin",
    "name": "admin",
    "phoneNumber": "123456789"
}